#!/bin/sh
export JAVA_OPTS="-Djava.awt.headless=true -Xmx4g -XX:+UseConcMarkSweepGC"

case "$1" in
start)
su -c "sh /opt/semsch/bin/startup.sh" www-data
;;

stop)
su -c "sh /opt/semsch/bin/shutdown.sh" www-data
;;

restart)
su -c "sh /opt/semsch/bin/shutdown.sh" www-data
su -c "sh /opt/semsch/bin/startup.sh" www-data
;;
esac

exit 0
